apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environment-apps
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    repoURL: https://github.com/grigorijk/gka-argo-cd-test-env
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true