apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: module-application-set
spec:
  generators:
  - list:
      elements:
      - cluster: shipping-service
        url: default.svc
  template:
    metadata:
      name: module-{{cluster-name}}-set
      namespace: openshift-gitops
    spec:
      destination:
        namespace: module-{{cluster-name}}-set
        server: https://kubernetes.default.svc
      project: default
      source:
        path: module-{{cluster-name}}/overlay/test
        repoURL: https://github.com/grigorijk/gka-argo-cd-test-env
        targetRevision: master
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
