apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: shipping-service
spec:
  params:
  - default: shipping-service-js
    name: APP_NAME
    type: string
  - default: https://github.com/grigorijk/shipping-service-js
    name: GIT_REPO
    type: string
  - default: master
    name: GIT_REVISION
    type: string
  - default: image-registry.openshift-image-registry.svc:5000/default/shipping-service
    name: IMAGE_NAME
    type: string
  - default: .
    name: PATH_CONTEXT
    type: string
  - default: "12"
    name: MAJOR_VERSION
    type: string
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: build-image
    params:
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: $(params.IMAGE_NAME)
    runAfter:
    - fetch-repository
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace
  workspaces:
  - name: workspace